CREATE TABLE IF NOT EXISTS cliente (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(255) NOT NULL,
	cpf varchar(11) NOT NULL,
	email varchar(255) NOT NULL,
	criado_em timestamp NOT NULL,
	atualizado_em timestamp NOT NULL,
	PRIMARY KEY (id)
);

INSERT INTO cliente (nome, cpf, email, criado_em, atualizado_em) VALUES
('John Wick', '58080541760', 'john.wick@outlook.com', NOW(), NOW()),
('Jane Doe', '12345678901', 'jane.doe@gmail.com', NOW(), NOW()),
('Peter Parker', '98765432100', 'peter.parker@dailybugle.com', NOW(), NOW()),
('Bruce Wayne', '56473829102', 'bruce.wayne@waynecorp.com', NOW(), NOW()),
('Clark Kent', '11223344556', 'clark.kent@dailyplanet.com', NOW(), NOW()),
('Diana Prince', '22334455667', 'diana.prince@themyscira.com', NOW(), NOW()),
('Tony Stark', '33445566778', 'tony.stark@starkindustries.com', NOW(), NOW()),
('Natasha Romanoff', '44556677889', 'natasha.romanoff@shield.com', NOW(), NOW()),
('Steve Rogers', '55667788990', 'steve.rogers@avengers.com', NOW(), NOW()),
('Barry Allen', '66778899001', 'barry.allen@centralcity.com', NOW(), NOW()),
('Wanda Maximoff', '77889900112', 'wanda.maximoff@avengers.com', NOW(), NOW()),
('Stephen Strange', '88990011223', 'stephen.strange@sorcerersanctum.com', NOW(), NOW()),
('Bruce Banner', '99001122334', 'bruce.banner@avengers.com', NOW(), NOW()),
('Thor Odinson', '10002233445', 'thor.odinson@asgard.com', NOW(), NOW()),
('Loki Laufeyson', '11003344556', 'loki.laufeyson@asgard.com', NOW(), NOW()),
('Challa', '12004455667', 'tchalla@wakanda.com', NOW(), NOW()),
('Shuri', '13005566778', 'shuri@wakanda.com', NOW(), NOW()),
('Scott Lang', '14006677889', 'scott.lang@pymtechnologies.com', NOW(), NOW()),
('Carol Danvers', '15007788990', 'carol.danvers@starforce.com', NOW(), NOW()),
('Nick Fury', '16008899001', 'nick.fury@shield.com', NOW(), NOW());